name: syndo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^5.0.0
  qr_code_scanner_plus: ^2.0.10+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  video_player: ^2.10.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/background0.png
    - assets/images/background1.png
    - assets/images/optionbackground.png
    - assets/images/storymodepict.png
    - assets/images/studymodepict.png
    - assets/images/playcard.png
    - assets/images/playbackground.png
    - assets/images/play-coinicon.png
    - assets/images/play-plusicon.png
    - assets/images/threehundcoins.png
    - assets/images/fiftycentcoins.png
    - assets/images/sixtfivecoins.png
    - assets/images/hunandfiftycoins.png
    - assets/images/buycoinbackground.png
    - assets/images/sumatera.png
    - assets/images/bali.png
    - assets/images/jawa.png
    - assets/images/scan_icon.png
    - assets/images/memo-evaluation-background.png
    - assets/images/quiz-flash-card-background.png
    - assets/images/evaluation-icon.png
    - assets/images/memorization-icon.png
    - assets/images/alphabet-icon.png
    - assets/images/alphabet-words-background.png
    - assets/images/word-icon.png
    - assets/images/flashcard1.png
    - assets/images/flashcard2.png
    - assets/images/flashcard3.png
    - assets/images/flashcard4.png
    - assets/images/scanner-card-1.png    
    - assets/images/scanner-card-2.png
    - assets/images/gesture-detection.png
    - assets/images/fillin-blanks.png
    - assets/images/study-background.png
    - assets/images/berkuliner.png
    - assets/images/berwisata.png
    - assets/images/bermain.png
    - assets/images/bersekolah.png
    - assets/images/bersosial.png
    - assets/images/flashcard-bg.png
    
    - assets/images/acard.png
    - assets/images/aquestcard.png
    - assets/images/bcard.png
    - assets/images/bquestcard.png
    - assets/images/ccard.png
    - assets/images/cquestcard.png
    - assets/images/dcard.png
    - assets/images/dquestcard.png
    - assets/images/ecard.png
    - assets/images/equestcard.png
    - assets/images/fcard.png
    - assets/images/fquestcard.png
    - assets/images/gcard.png
    - assets/images/gquestcard.png
    - assets/images/hcard.png
    - assets/images/hquestcard.png
    - assets/images/icard.png
    - assets/images/iquestcard.png
    - assets/images/jcard.png
    - assets/images/jquestcard.png
    - assets/images/kcard.png
    - assets/images/kquestcard.png
    - assets/images/lcard.png
    - assets/images/lquestcard.png
    - assets/images/mcard.png
    - assets/images/mquestcard.png
    - assets/images/ncard.png
    - assets/images/nquestcard.png
    - assets/images/ocard.png
    - assets/images/oquestcard.png
    - assets/images/pcard.png
    - assets/images/pquestcard.png
    - assets/images/qcard.png
    - assets/images/qquestcard.png
    - assets/images/rcard.png
    - assets/images/rquestcard.png
    - assets/images/scard.png
    - assets/images/squestcard.png
    - assets/images/tcard.png
    - assets/images/tquestcard.png
    - assets/images/ucard.png
    - assets/images/uquestcard.png
    - assets/images/vcard.png
    - assets/images/vquestcard.png
    - assets/images/wcard.png
    - assets/images/wquestcard.png
    - assets/images/xcard.png
    - assets/images/xquestcard.png
    - assets/images/ycard.png
    - assets/images/yquestcard.png
    - assets/images/zcard.png
    - assets/images/zquestcard.png
    - assets/images/skor-board.png
    
    - assets/images/akucard.png
    - assets/images/akuquestcard.png
    - assets/images/becakcard.png
    - assets/images/becakquestcard.png
    - assets/images/biscard.png
    - assets/images/bisquestcard.png
    - assets/images/hallocard.png
    - assets/images/halloquestcard.png
    - assets/images/maucard.png
    - assets/images/mauquestcard.png
    - assets/images/mobilcard.png
    - assets/images/mobilquestcard.png
    - assets/images/namacard.png
    - assets/images/namaquestcard.png
    - assets/images/salamkenalcard.png
    - assets/images/salamkenalquestcard.png
    - assets/images/senangcard.png
    - assets/images/senangquestcard.png
    - assets/images/terimakasihcard.png
    - assets/images/terimakasihquestcard.png
    - assets/images/tolongcard.png
    - assets/images/tolongquestcard.png

    - assets/audio/BACKSOUND_GAMELAN_INDONESIAN_MUSIC_ETHNIC_CULTURE.mp3

    - assets/video/IMG_3096.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
