final List<Map<String, dynamic>> questionData = [
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/aquestcard.png",
    "questImageAnswer": "assets/images/acard.png",
  },
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/bquestcard.png",
    "questImageAnswer": "assets/images/bcard.png",
  },
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 2,
    "questImageQuestion": "assets/images/cquestcard.png",
    "questImageAnswer": "assets/images/ccard.png",
  },
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/dquestcard.png",
    "questImageAnswer": "assets/images/dcard.png",
  },
  {
    "options": ["B", "C", "D", "E"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/equestcard.png",
    "questImageAnswer": "assets/images/ecard.png",
  },
  {
    "options": ["C", "F", "D", "E"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fquestcard.png",
    "questImageAnswer": "assets/images/fcard.png",
  },
  {
    "options": ["D", "E", "G", "F"],
    "answerindex": 2,
    "questImageQuestion": "assets/images/gquestcard.png",
    "questImageAnswer": "assets/images/gcard.png",
  },
  {
    "options": ["H", "I", "J", "K"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/hquestcard.png",
    "questImageAnswer": "assets/images/hcard.png",
  },
  {
    "options": ["H", "I", "J", "K"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/iquestcard.png",
    "questImageAnswer": "assets/images/icard.png",
  },
  {
    "options": ["H", "I", "J", "L"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/jquestcard.png",
    "questImageAnswer": "assets/images/jcard.png",
  },
  {
    "options": ["H", "I", "J", "K"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/kquestcard.png",
    "questImageAnswer": "assets/images/kcard.png",
  },
  {
    "options": ["I", "J", "K", "L"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/lquestcard.png",
    "questImageAnswer": "assets/images/lcard.png",
  },
  {
    "options": ["J", "K", "L", "M"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/mquestcard.png",
    "questImageAnswer": "assets/images/mcard.png",
  },
  {
    "options": ["K", "L", "M", "N"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/nquestcard.png",
    "questImageAnswer": "assets/images/ncard.png",
  },
  {
    "options": ["L", "M", "N", "O"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/oquestcard.png",
    "questImageAnswer": "assets/images/ocard.png",
  },
  {
    "options": ["L", "M", "N", "P"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/pquestcard.png",
    "questImageAnswer": "assets/images/pcard.png",
  },
  {
    "options": ["M", "N", "P", "Q"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/qquestcard.png",
    "questImageAnswer": "assets/images/qcard.png",
  },
  {
    "options": ["N", "P", "Q", "R"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/rquestcard.png",
    "questImageAnswer": "assets/images/rcard.png",
  },
  {
    "options": ["P", "Q", "R", "S"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/squestcard.png",
    "questImageAnswer": "assets/images/scard.png",
  },
  {
    "options": ["Q", "R", "S", "T"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/tquestcard.png",
    "questImageAnswer": "assets/images/tcard.png",
  },
  {
    "options": ["R", "S", "T", "U"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/uquestcard.png",
    "questImageAnswer": "assets/images/ucard.png",
  },
  {
    "options": ["S", "T", "U", "V"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/vquestcard.png",
    "questImageAnswer": "assets/images/vcard.png",
  },
  {
    "options": ["T", "U", "V", "W"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/wquestcard.png",
    "questImageAnswer": "assets/images/wcard.png",
  },
  {
    "options": ["U", "V", "W", "X"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/xquestcard.png",
    "questImageAnswer": "assets/images/xcard.png",
  },
  {
    "options": ["V", "W", "X", "Y"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/yquestcard.png",
    "questImageAnswer": "assets/images/ycard.png",
  },
  {
    "options": ["W", "X", "Y", "Z"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/zquestcard.png",
    "questImageAnswer": "assets/images/zcard.png",
  },
];

final List<Map<String, dynamic>> questionWordData = [
  {
    "options": ["AKU", "TOLONG", "SENANG"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/akuquestcard.png",
    "questImageAnswer": "assets/images/akucard.png",
  },
  {
    "options": ["MAU", "TERIMA KASIH", "BECAK"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/terimakasihquestcard.png",
    "questImageAnswer": "assets/images/terimakasihcard.png",
  },
  {
    "options": ["SALAM KENAL", "NAMA", "HALLO"],
    "answerindex": 2,
    "questImageQuestion": "assets/images/halloquestcard.png",
    "questImageAnswer": "assets/images/hallocard.png",
  },
  {
    "options": ["AKU", "TOLONG", "SENANG"],
    "answerindex": 2,
    "questImageQuestion": "assets/images/senangquestcard.png",
    "questImageAnswer": "assets/images/senangcard.png",
  },
  {
    "options": ["BUS", "MOBIL", "TIDAK MAU"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/bisquestcard.png",
    "questImageAnswer": "assets/images/biscard.png",
  },
  {
    "options": ["AKU", "TOLONG", "SENANG"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/tolongquestcard.png",
    "questImageAnswer": "assets/images/tolongcard.png",
  },
  {
    "options": ["SALAM KENAL", "NAMA", "HALLO"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/senangquestcard.png",
    "questImageAnswer": "assets/images/senangcard.png",
  },
  {
    "options": ["MAU", "TERIMA KASIH", "BECAK"],
    "answerindex": 2,
    "questImageQuestion": "assets/images/terimakasihquestcard.png",
    "questImageAnswer": "assets/images/terimakasihcard.png",
  },
  {
    "options": ["SALAM KENAL", "NAMA", "HALLO"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/namaquestcard.png",
    "questImageAnswer": "assets/images/namacard.png",
  },
  {
    "options": ["BUS", "MOBIL", "TIDAK MAU"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/mobilquestcard.png",
    "questImageAnswer": "assets/images/mobilcard.png",
  },
  {
    "options": ["MAU", "TERIMA KASIH", "BECAK"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/mauquestcard.png",
    "questImageAnswer": "assets/images/maucard.png",
  },
];

final List<Map<String, dynamic>> storyPasarScenes = [
  {
    "actor": "Giel",
    "dialog": "Kamu sampai sini naik apa, Arin?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "showImage": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Aku kesini naik mobil tadi, Giel. Papaku yang ngantar.",
    "quiz": [
      {"image": "assets/images/opt-busstory.png", "ans": false},
      {"image": "assets/images/opt-becakstory.png", "ans": false},
      {"image": "assets/images/opt-mobilstory.png", "ans": true},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "assets/images/opt-mobilstory.png",
    "showImageGiel": "",
    "target": "mobil",
  },
  {
    "actor": "Giel",
    "dialog": "Wah, enak ya. Aku jalan kaki dari rumah, deket banget soalnya.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Jadi, kamu mau langsung jajan sekarang?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Baiklah, apakah kamu mau jajan?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Iya dong! Aku nggak sabar buat makan jajanan pasar. Hehe.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "showImage": "",
    "target": "",
  },
  {
    "actor": "...",
    "dialog": "Mereka melewati lapak penjual makanan",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Lihat, di sini ada bakpia, jadah tempe, sama onde-onde. Apakah kamu mau onde-onde?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Hmm... maaf, aku tidak mau onde-onde. Aku lebih suka klepon, soalnya ada gula cair di dalamnya.",
    "quiz": [
      {"image": "assets/images/opt-salamkenalstory.png", "ans": false},
      {"image": "assets/images/opt-pesawatstory.png", "ans": false},
      {"image": "assets/images/opt-tidakmaustory.png", "ans": true},
    ],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/opt-tidakmaustory.png",
    "showImage": "",
    "target": "tidak mau",
  },
  {
    "actor": "Giel",
    "dialog": "Baiklah, aku juga suka klepon. Yuk kita beli!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "...",
    "dialog": "Mereka mendekati penjual klepon",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Penjual",
    "dialog": "Halo, Nak. Salam kenal, mau beli apa?",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Salam kenal juga, Bu. Nama saya Arin, ini temanku Giel.",
    "quiz": [
      {"image": "assets/images/opt-salamkenalstory.png", "ans": true},
      {"image": "assets/images/opt-namastory.png", "ans": false},
      {"image": "assets/images/opt-terimakasihstory.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/opt-salamkenalstory.png",
    "showImage": "",
    "target": "salam kenal",
  },
  {
    "actor": "Arin",
    "dialog": "Senang bertemu, Bu. Kami mau beli kleponnya.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Penjual",
    "dialog": "Baiklah, ini kleponnya.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "showImage": "",
    "target": "klepon",
  },
  {
    "actor": "Giel",
    "dialog": "Terima kasih banyak, Bu!",
    "quiz": [
      {"image": "assets/images/opt-terimakasihstory.png", "ans": true},
      {"image": "assets/images/opt-tidakmaustory.png", "ans": false},
      {"image": "assets/images/opt-tolongstory.png", "ans": false},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/opt-terimakasihstory.png",
    "showImage": "",
    "target": "terima kasih",
  },
  {
    "actor": "Penjual",
    "dialog": "Sama sama",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": ".....",
    "dialog": "Setelah beli, mereka duduk di bangku kayu sambil makan",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hmmm, enak banget! Arin, boleh ambilin aku satu lagi tidak?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Nih, aku kasih satu.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Terima kasih, Giel!",
    "quiz": [
      {"image": "assets/images/opt-pesawatstory.png", "ans": false},
      {"image": "assets/images/opt-tolongstory.png", "ans": false},
      {"image": "assets/images/opt-terimakasihstory.png", "ans": true},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "assets/images/opt-terimakasihstory.png",
    "showImageGiel": "",
    "showImage": "",
    "target": "terima kasih",
  },
  {
    "actor": "Giel",
    "dialog":
        "Sama-sama. Aku senang banget kita bisa jajan bareng di pasar ini.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "",
    "showImage": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyJakartaScenes = [
  {
    "actor": "...",
    "dialog":
        "Ramai kendaraan, suara klakson, pedagang kaki lima teriak jualan",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Wah, akhirnya kita sampai di Jakarta!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Iya, rame banget ya. Banyak gedung tinggi juga.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Jadi, tujuan pertama kita apa?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Hmmm… gimana kalau kita ke Monas? Katanya pemandangannya bagus dari atas.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Oke, aku setuju! Tapi… kita naik apa ke sana?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hmmm, transportasi apa ya yang dekat sini?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Oh! Disitu ada becak.",
    "quiz": [
      {"image": "assets/images/opt-busstory.png", "ans": false},
      {"image": "assets/images/opt-pesawatstory.png", "ans": false},
      {"image": "assets/images/opt-motorstory.png", "ans": false},
      {"image": "assets/images/opt-becakstory.png", "ans": true},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "assets/images/opt-becakstory.png",
    "showImageGiel": "",
    "target": "becak",
  },
  {
    "actor": "Giel",
    "dialog":
        "Becak? Wah, asik banget tuh! Aku belum pernah naik becak di Jakarta.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Aku juga belum, biasanya cuma lihat di foto.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Kamu mau coba?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Iya, aku mau! Pasti seru.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Kalau gitu ayo kita tanya dulu ke abang becaknya.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "...",
    "dialog": "Mereka mendekati abang becak",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Halo Pak, salam kenal. Nama saya Giel, ini Arin.",
    "quiz": [
      {"image": "assets/images/opt-akustory.png", "ans": false},
      {"image": "assets/images/opt-salamkenalstory.png", "ans": true},
      {"image": "assets/images/opt-tidakmaustory.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "assets/images/opt-salamkenalstory.png",
    "target": "salam kenal",
  },
  {
    "actor": "Abang Becak",
    "dialog": "Halo juga. Salam kenal, Nak. Mau ke mana?",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Kami mau ke Monas, Pak. Bisa antar?",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Abang Becak",
    "dialog": "Bisa. Ayo naik.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Terima kasih, Pak!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "...",
    "dialog": "Di atas becak, mereka ngobrol sambil jalan",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Wah, ternyata seru banget naik becak di Jakarta. Anginnya kencang!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Iya, aku senang banget. Nanti sampai Monas, kita bisa foto bareng.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Baiklah! Jangan lupa kita juga jajan, ya. Aku sudah lapar.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hehe, siap.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyMuseumScenes = [
  {
    "actor": "Arin",
    "dialog":
        "Wah, Giel, di sini banyak sekali kendaraan. Kita bisa belajar satu per satu.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Iya, ayo mulai dari yang paling dekat.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Ini namanya mobil. Mobil dipakai orang untuk jalan di darat, biasanya buat keluarga.",
    "quiz": [],
    "arinImg": "assets/images/giel-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "assets/images/opt-mobilstory.png",
    "target": "mobil",
  },
  {
    "actor": "Arin",
    "dialog":
        "Iya, aku sering lihat mobil di jalan raya. Warnanya juga macam-macam.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Nah, di sebelah mobil ada motor. Motor lebih kecil dan bisa dipakai dua orang.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "assets/images/opt-motorstory.png",
    "showImageGiel": "",
    "target": "motor",
  },
  {
    "actor": "Giel",
    "dialog":
        "Benar, motor bisa selap-selip di jalan sempit. Tapi harus hati-hati, ya.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Kalau yang besar ini namanya truk. Truk dipakai untuk mengangkut barang yang berat atau banyak.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Ooooh, jadi kalau lihat truk di jalan itu biasanya bawa pasir, kayu, atau kotak-kotak besar, ya?",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Betul sekali!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Oh! di sana ada miniatur kereta. Kereta bisa membawa banyak orang sekaligus, jalannya di atas rel.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Seru banget naik kereta. Kita bisa lihat pemandangan sambil duduk santai.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Kalau yang tinggi besar ini adalah pesawat. Pesawat bisa terbang di langit.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/arin-type-1.png",
    "showImage": "",
    "showImageArin": "assets/images/opt-pesawatstory.png",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Waaah, aku pernah naik pesawat sekali. Dari atas kelihatan awan putih semua.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Terakhir, ini ada miniatur kapal. Kapal digunakan untuk perjalanan di laut.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Jadi kalau mau pergi ke pulau lain lewat laut, kita bisa naik kapal, kan?",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Iya, benar sekali.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Wah, hari ini kita belajar banyak transportasi!",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Betul! Aku senang sekali belajar di museum ini.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Aku juga. Terima kasih sudah belajar bareng aku, Arin.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Sama-sama, Giel!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImage": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyTamanScenes = [
  {
    "actor": "Arin",
    "dialog": "Giel, kamu biasanya ngapain aja sih setiap hari?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Hehe, jadwalku lumayan beda-beda tiap hari. Mau aku ceritain dari Senin sampai Minggu?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Boleh, aku penasaran!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Hari Senin, aku biasanya bangun pagi-pagi terus siap-siap sekolah.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Sama, aku juga. Senin selalu sibuk banget, ya.",
    "quiz": [
      {"image": "assets/images/story-smtr-senin.png", "ans": true},
      {"image": "assets/images/story-smtr-rabu.png", "ans": false},
      {"image": "assets/images/story-smtr-kamis.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "assets/images/story-smtr-senin.png",
    "showImageGiel": "",
    "target": "senin",
  },
  {
    "actor": "Giel",
    "dialog":
        "Hari Selasa, aku ada les gambar. Aku suka banget karena bisa corat-coret bebas.",
    "quiz": [
      {"image": "assets/images/story-smtr-senin.png", "ans": false},
      {"image": "assets/images/story-smtr-rabu.png", "ans": false},
      {"image": "assets/images/story-smtr-selasa.png", "ans": true},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-selasa.png",
    "target": "selasa",
  },
  {
    "actor": "Arin",
    "dialog": "Wah, keren! Aku hari Selasa ada latihan menari di sanggar.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Kalau Rabu, aku biasanya bantu ibu belanja ke pasar.",
    "quiz": [
      {"image": "assets/images/story-smtr-senin.png", "ans": false},
      {"image": "assets/images/story-smtr-rabu.png", "ans": true},
      {"image": "assets/images/story-smtr-kamis.png", "ans": false},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-rabu.png",
    "target": "rabu",
  },
  {
    "actor": "Arin",
    "dialog": "Lucu banget! Aku hari Rabu ikut ekskul musik di sekolah.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Hari Kamis, aku main sepak bola sama teman-teman di lapangan.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Aku hari Kamis lebih sering belajar bareng teman, soalnya besoknya ulangan.",
    "quiz": [
      {"image": "assets/images/story-smtr-senin.png", "ans": false},
      {"image": "assets/images/story-smtr-rabu.png", "ans": false},
      {"image": "assets/images/story-smtr-kamis.png", "ans": true},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin": "assets/images/story-smtr-kamis.png",
    "showImageGiel": "",
    "target": "kamis",
  },
  {
    "actor": "Giel",
    "dialog":
        "Nah, kalau Jumat, aku suka banget karena pulang sekolahnya lebih cepat.",
    "quiz": [
      {"image": "assets/images/story-smtr-kamis.png", "ans": false},
      {"image": "assets/images/story-smtr-selasa.png", "ans": false},
      {"image": "assets/images/story-smtr-jumat.png", "ans": true},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-jumat.png",
    "target": "jumat",
  },
  {
    "actor": "Arin",
    "dialog": "Betul! Aku juga senang hari Jumat, jadi bisa main lebih lama.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Hari Sabtu, aku biasanya jalan sama keluargaku. Kadang ke mall, kadang ke taman.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Aku kalau Sabtu suka nonton film bareng kakakku.",
    "quiz": [
      {"image": "assets/images/story-smtr-minggu.png", "ans": false},
      {"image": "assets/images/story-smtr-sabtu.png", "ans": true},
      {"image": "assets/images/story-smtr-kamis.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin": "assets/images/story-smtr-sabtu.png",
    "showImageGiel": "",
    "target": "sabtu",
  },
  {
    "actor": "Giel",
    "dialog":
        "Terus, hari Minggu… waktunya istirahat. Biasanya aku main sepeda keliling komplek.",
    "quiz": [
      {"image": "assets/images/story-smtr-senin.png", "ans": false},
      {"image": "assets/images/story-smtr-minggu.png", "ans": true},
      {"image": "assets/images/story-smtr-kamis.png", "ans": false},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-minggu.png",
    "target": "minggu",
  },
  {
    "actor": "Arin",
    "dialog":
        "Hahaha, aku kalau Minggu suka bangun siang. Rasanya enak banget!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Jadi jadwal kita beda-beda tapi seru ya.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Iya! Dari Senin sampai Minggu selalu ada hal menarik.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Aku senang denger ceritamu, Giel. Besok kita bikin jadwal main bareng juga, yuk!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Setuju!",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyKebunBinatangScenes = [
  {
    "actor": "Arin",
    "dialog": "Wah, Giel, akhirnya kita sampai di kebun binatang mini!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Iya, aku nggak sabar lihat hewan-hewannya dari dekat.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Lihat, di sana ada ayam. Bulu-bulunya warnanya bagus banget.",
    "quiz": [
      {"image": "assets/images/story-smtr-kd-ayam.png", "ans": true},
      {"image": "assets/images/story-smtr-kd-anjing.png", "ans": false},
      {"image": "assets/images/story-smtr-kd-bebek.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin": "assets/images/story-smtr-kd-ayam.png",
    "showImageGiel": "",
    "target": "ayam",
  },
  {
    "actor": "Giel",
    "dialog": "Hehe, ayamnya lari-lari ke sana-sini. Lucu ya.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Eh, ada kucing juga! Kucingnya lagi tidur manis.",
    "quiz": [
      {"image": "assets/images/story-smtr-kd-anjing.png", "ans": false},
      {"image": "assets/images/story-smtr-kd-kucing.png", "ans": true},
      {"image": "assets/images/story-smtr-kd-bebek.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin": "assets/images/story-smtr-kd-kucing.png",
    "showImageGiel": "",
    "target": "kucing",
  },
  {
    "actor": "Giel",
    "dialog":
        "Aku suka banget sama kucing. Kalau dielus, biasanya mereka mendengkur.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "(menunjuk) Giel, itu ada anjing kecil. Ramah banget, ekornya digoyang-goyang.",
    "quiz": [
      {"image": "assets/images/story-smtr-kd-ayam.png", "ans": false},
      {"image": "assets/images/story-smtr-kd-anjing.png", "ans": true},
      {"image": "assets/images/story-smtr-kd-bebek.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin": "assets/images/story-smtr-kd-anjing.png",
    "showImageGiel": "",
    "target": "anjing",
  },
  {
    "actor": "Giel",
    "dialog": "Iya, anjing itu kayak ngajak kita berteman.",
    "quiz": [
      {"image": "assets/images/story-smtr-berteman.png", "ans": true},
      {"image": "assets/images/story-smtr-jumat.png", "ans": false},
      {"image": "assets/images/story-smtr-kd-bebek.png", "ans": false},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-berteman.png",
    "target": "berteman",
  },
  {
    "actor": "Giel",
    "dialog":
        "Hehe, terus di sebelah kolam ada bebek! Mereka berbaris rapi sambil 'wek wek wek.'",
    "quiz": [
      {"image": "assets/images/story-smtr-kd-bebek.png", "ans": false},
      {"image": "assets/images/story-smtr-kd-anjing.png", "ans": false},
      {"image": "assets/images/story-smtr-kd-bebek.png", "ans": true},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-kd-bebek.png",
    "target": "bebek",
  },
  {
    "actor": "Arin",
    "dialog":
        "Hahaha, suaranya rame banget. Bebeknya berenang bareng, kayak sahabat.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Seru banget ya, hari ini kita bisa lihat ayam, kucing, anjing, sampai bebek sekaligus.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Iya, aku senang banget. Rasanya semua hewan di sini kayak ingin berteman sama kita.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "...",
    "dialog": "Matahari mulai terbenam, suasana di kebun binatang jadi tenang.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Giel, besok kita ke sini lagi, ya. Aku pengen kasih makan bebek.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Baiklah! Aku juga mau main sama kucing lagi.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Asik!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyBuahScenes = [
  {
    "actor": "Arin",
    "dialog": "Giel, kamu suka buah apa?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Hmm… aku suka apel. Rasanya manis dan segar.",
    "quiz": [
      {"image": "assets/images/story-smtr-apel.png", "ans": true},
      {"image": "assets/images/story-smtr-jeruk.png", "ans": false},
      {"image": "assets/images/story-smtr-pisang.png", "ans": false},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-apel.png",
    "target": "apel",
  },
  {
    "actor": "Arin",
    "dialog":
        "Aku juga suka apel! Katanya apel bikin tubuh sehat karena banyak vitaminnya.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Nah, buah kedua favoritku… aku kasih ciri-ciri aja deh. Ciri-cirinya kecil-kecil, warnanya bisa ungu atau hijau, rasanya manis. Apa hayoo tebak?",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Hmmm… kecil-kecil, bisa ungu atau hijau… Oh aku tahu! Itu anggur, kan?",
    "quiz": [
      {"image": "assets/images/story-smtr-apel.png", "ans": false},
      {"image": "assets/images/story-smtr-anggur.png", "ans": true},
      {"image": "assets/images/story-smtr-pisang.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin": "assets/images/story-smtr-anggur.png",
    "showImageGiel": "",
    "target": "anggur",
  },
  {
    "actor": "Giel",
    "dialog": "Betul sekali! Hehe, pintar banget kamu.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hehe, makan anggur kayak makan permen alami.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Kalau aku suka banget jeruk. Rasanya asam manis, terus ada banyak vitamin C.",
    "quiz": [
      {"image": "assets/images/story-smtr-anggur.png", "ans": false},
      {"image": "assets/images/story-smtr-jeruk.png", "ans": true},
      {"image": "assets/images/story-smtr-pisang.png", "ans": false},
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin": "assets/images/story-smtr-jeruk.png",
    "showImageGiel": "",
    "target": "jeruk",
  },
  {
    "actor": "Giel",
    "dialog": "Jadi jeruk bisa bikin kita sehat dan nggak gampang sakit ya?",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Betul!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Terus ada pisang juga. Aku sering makan pisang kalau lapar sebelum main bola.",
    "quiz": [
      {"image": "assets/images/story-smtr-apel.png", "ans": true},
      {"image": "assets/images/story-smtr-jeruk.png", "ans": false},
      {"image": "assets/images/story-smtr-pisang.png", "ans": true},
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel": "assets/images/story-smtr-pisang",
    "target": "pisang",
  },
  {
    "actor": "Arin",
    "dialog": "Wah, pintar. Pisang bisa kasih energi biar kuat main.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Jadi buah itu bukan cuma enak, tapi juga bikin kita sehat.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Iya! Makasih ya, Arin, udah cerita soal buah.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Sama-sama, Giel. Yuk besok kita bawa buah buat dimakan bareng!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Setuju!",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyPantaiScenes = [
  {
    "actor": "Arin",
    "dialog": "Selamat siang, Giel! Wah, pantainya cantik banget ya~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Selamat siang, Arin! Iya, lautnya biru banget. Tempat ini bagus sekali!",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Kamu mau bermain pasir dulu atau makan dulu?",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Aku mau bermain pasir dulu deh. Habis itu baru makan!",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1n_MkqQVDfpl6VJIT55k1fdJzrLbxBRKt",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=164RXHPk2mgzuiAqt8X2TIZnK5RM0wHc3",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1jGRCwAFNTL82dmfJht4x_bh2zQ_K8o0w",
        "ans": true,
      },
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=1jGRCwAFNTL82dmfJht4x_bh2zQ_K8o0w",
    "target": "bermain",
  },
  {
    "actor": "Arin",
    "dialog": "Hehe, oke! Kita bikin istana pasir yang besar, ya!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Arin, kamu tahu nggak, di mana tempat makan yang enak di sini?",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1MZQc7Urg58S1wU5VZeZ1PEBZXqsjGuFk",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1wYfTCmqeg1AEKR8YRWyBT1VQL1LrPKLX",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1wH4yvxb9EmfUMw6R-2A81UQIM3tYEMHP",
        "ans": true,
      },
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
    "target": "di mana",
  },
  {
    "actor": "Arin",
    "dialog":
        "Hmm, aku lihat tadi ada tempat makan kecil di dekat pohon kelapa. Mungkin di situ~",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1guX3ac_sPjLpzT9lleRiwMJ3bnhYYYL9",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1qVbY_jK1mxBN0V2IN6GP7-AnIAhphoKN",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1FxzMp8SAv5xz4HcYg7v1xw2M59b1T8Xr",
        "ans": false,
      },
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "",
    "showImageArin":
        "https://drive.google.com/uc?export=view&id=1qVbY_jK1mxBN0V2IN6GP7-AnIAhphoKN",
    "showImageGiel": "",
    "target": "makan",
  },
  {
    "actor": "Giel",
    "dialog": "Wah, iya! Kapan kita ke sana? Aku mulai lapar nih.",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Setelah istana pasirnya jadi! Biar kita makan sambil lihat hasil karya kita~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Hehe, ide bagus!",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1a6QVlauXd210LLG7M4-6ksvy8SLKkxyt",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1n_MkqQVDfpl6VJIT55k1fdJzrLbxBRKt",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=164RXHPk2mgzuiAqt8X2TIZnK5RM0wHc3",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1jGRCwAFNTL82dmfJht4x_bh2zQ_K8o0w",
        "ans": false,
      },
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=1a6QVlauXd210LLG7M4-6ksvy8SLKkxyt",
    "target": "bagus",
  },
  {
    "actor": "Giel",
    "dialog": "Oh iya, kamu tahu nggak harga nasi goreng di sini berapa?",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1guX3ac_sPjLpzT9lleRiwMJ3bnhYYYL9",
        "ans": false,
      },
      // {"image": "https://drive.google.com/uc?export=view&id=1wYfTCmqeg1AEKR8YRWyBT1VQL1LrPKLX", "ans": true},
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
        "ans": false,
      },
    ],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=1wYfTCmqeg1AEKR8YRWyBT1VQL1LrPKLX",
    "target": "berapa",
  },
  {
    "actor": "Arin",
    "dialog": "Aku dengar tadi dua puluh ribu.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Wah, pas banget buat jajan siang!",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hehe iya, makan di pinggir pantai pasti makin enak~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Setuju! Liburan di Bali memang seru banget!",
    "quiz": [],
    "arinImg": "",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyMonkeyScenes = [
  {
    "actor": "Arin",
    "dialog": "Selamat pagi, Giel!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hari ini kita jalan-jalan ke mana, ya?",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1wYfTCmqeg1AEKR8YRWyBT1VQL1LrPKLX",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1guX3ac_sPjLpzT9lleRiwMJ3bnhYYYL9",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1wH4yvxb9EmfUMw6R-2A81UQIM3tYEMHP",
        "ans": false,
      },
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin":
        "https://drive.google.com/uc?export=view&id=1guX3ac_sPjLpzT9lleRiwMJ3bnhYYYL9",
    "showImageGiel": "",
    "target": "jalan jalan",
  },
  {
    "actor": "Giel",
    "dialog": "Katanya kita mau ke Monkey Forest di Ubud, Bali!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Wah seru! Aku belum pernah lihat monyet sebanyak itu~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Iya, tapi hati-hati ya, Arin. Katanya monyetnya suka iseng ambil topi atau makanan",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Haha iya, nanti aku simpan bekalku baik-baik.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Lihat deh! Ada sawah di belakang sana, hijau banget.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Itu Tegallalang Rice Terrace! Indah ya",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Iya, aku suka tempatnya. Udara di sini juga segar banget.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Eh, Giel, tadi kamu lihat nggak, ada turis yang pakai bahasa isyarat.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Iya! Aku lihat juga. Mereka pakai BISINDO, kan?",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1jGRCwAFNTL82dmfJht4x_bh2zQ_K8o0w",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1-dKIzZUvGUuA4te6nwMMOl8AxwR5qvJ_",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1j3ZO-QiIAxTSB_31ZnJYG6uBMF3t17TP",
        "ans": false,
      },
    ],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=1-dKIzZUvGUuA4te6nwMMOl8AxwR5qvJ_",
    "target": "BISINDO",
  },
  {
    "actor": "Arin",
    "dialog": "Betul seru banget bisa komunikasi dengan tangan.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog":
        "Aku jadi pengen belajar lagi deh, biar bisa komunikasi sama teman tunarungu juga.",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1n_MkqQVDfpl6VJIT55k1fdJzrLbxBRKt",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=164RXHPk2mgzuiAqt8X2TIZnK5RM0wHc3",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1j3ZO-QiIAxTSB_31ZnJYG6uBMF3t17TP",
        "ans": false,
      },
    ],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=1n_MkqQVDfpl6VJIT55k1fdJzrLbxBRKt",
    "target": "belajar",
  },
  {
    "actor": "Arin",
    "dialog": "Ayo nanti kita latihan bareng!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Baiklah Arin, tinggal dijadwalkan ini.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Di rumahku aja, Giel!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Giel",
    "dialog": "Ah kalau di rumahmu mah kita malah main~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hehe, janji kok bakal rajin belajarnya!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

final List<Map<String, dynamic>> storyWarungScenes = [
  {
    "actor": "Arin",
    "dialog": "Wah, Giel! Lihat deh, warungnya ramai banget~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "giel",
    "dialog": "Iya, penjualnya juga kelihatan ramah banget.",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1wYfTCmqeg1AEKR8YRWyBT1VQL1LrPKLX",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1wH4yvxb9EmfUMw6R-2A81UQIM3tYEMHP",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1j3ZO-QiIAxTSB_31ZnJYG6uBMF3t17TP",
        "ans": true,
      },
    ],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-2.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=1j3ZO-QiIAxTSB_31ZnJYG6uBMF3t17TP",
    "target": "ramah",
  },
  {
    "actor": "Arin",
    "dialog": "Aku suka tempat yang seperti ini, suasananya hangat.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "giel",
    "dialog": "Lihat menunya! Ada berbagai macam makanan khas Bali.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Hmm, aku pilih sate lilit aja deh. Katanya itu terkenal banget.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "giel",
    "dialog": "Aku juga mau! Aku penasaran gimana cara buatnya.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Katanya mereka masak pakai bumbu khas Bali, makanya aromanya enak banget!",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1wYfTCmqeg1AEKR8YRWyBT1VQL1LrPKLX",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=13RNpZUULHFxkri1cfgukeqSb5lPWJSBd",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1j3ZO-QiIAxTSB_31ZnJYG6uBMF3t17TP",
        "ans": false,
      },
    ],
    "arinImg": "assets/images/giel-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel":
        "https://drive.google.com/uc?export=view&id=13RNpZUULHFxkri1cfgukeqSb5lPWJSBd",
    "target": "masak",
  },
  {
    "actor": "giel",
    "dialog": "Wah, aku jadi pengen belajar masak juga nanti di rumah.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog":
        "Kamu pasti cepat bisa, Giel! Soalnya kamu pintar banget belajar hal baru.",
    "quiz": [
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1sEOLbWqo8SWoVYry6aAJktJ2cIjdGScf",
        "ans": true,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1RdG0NTB9kzZxJihXHJ5uR6C8T5EIUe7R",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=13RNpZUULHFxkri1cfgukeqSb5lPWJSBd",
        "ans": false,
      },
      {
        "image":
            "https://drive.google.com/uc?export=view&id=1j3ZO-QiIAxTSB_31ZnJYG6uBMF3t17TP",
        "ans": false,
      },
    ],
    "arinImg": "assets/images/arin-type-2.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin":
        "https://drive.google.com/uc?export=view&id=1sEOLbWqo8SWoVYry6aAJktJ2cIjdGScf",
    "showImageGiel": "",
    "target": "pintar",
  },
  {
    "actor": "giel",
    "dialog": "Hehe, makasih, Arin. Kamu juga kok!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Ayo, makan dulu sebelum satenya dingin~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "giel",
    "dialog": "Siap! Wah, rasanya enak banget ya!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Iya, aku jadi pengen coba berbagai makanan Bali lainnya.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "giel",
    "dialog":
        "Eh tapi tadi bapaknya juga bilang, kalau kita mau berbagi makanan ke monyet, harus hati-hati.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Iya, benar! Bakal ku jaga ketat sate seenak ini, hehe.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "giel",
    "dialog": "Wah, nggak terasa sudah agak sore, Arin.",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "Arin",
    "dialog": "Iya, selamat sore, Giel. Hari ini seru banget ya!",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
  {
    "actor": "giel",
    "dialog":
        "Banget! Aku senang bisa jalan-jalan dan belajar hal baru bareng kamu~",
    "quiz": [],
    "arinImg": "assets/images/arin-type-1.png",
    "gielImg": "assets/images/giel-type-1.png",
    "showImageArin": "",
    "showImageGiel": "",
    "target": "",
  },
];

// start here
final List<Map<String, dynamic>> questionFillinData = [
  {
    "options": [
      "assets/images/aquestcard.png",
      "assets/images/bquestcard.png",
      "assets/images/cquestcard.png",
    ],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fillin-bebek.png",
    "questionText": "_ E B E K",
  },
  {
    "options": [
      "assets/images/jquestcard.png",
      "assets/images/kquestcard.png",
      "assets/images/lquestcard.png",
    ],
    "answerindex": 0,
    "questImageQuestion": "assets/images/fillin-meja.png",
    "questionText": "M E _ A",
  },
  {
    "options": [
      "assets/images/hquestcard.png",
      "assets/images/iquestcard.png",
      "assets/images/mquestcard.png",
    ],
    "answerindex": 0,
    "questImageQuestion": "assets/images/fillin-pohon.png",
    "questionText": "P O _ O N",
  },
  {
    "options": [
      "assets/images/squestcard.png",
      "assets/images/oquestcard.png",
      "assets/images/dquestcard.png",
    ],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fillin-bola.png",
    "questionText": "B _ L A",
  },
  {
    "options": [
      "assets/images/squestcard.png",
      "assets/images/wquestcard.png",
      "assets/images/rquestcard.png",
    ],
    "answerindex": 0,
    "questImageQuestion": "assets/images/fillin-sapi.png",
    "questionText": "S A P _",
  },
  {
    "options": [
      "assets/images/aquestcard.png",
      "assets/images/pquestcard.png",
      "assets/images/bquestcard.png",
    ],
    "answerindex": 0,
    "questImageQuestion": "assets/images/fillin-ayam.png",
    "questionText": "_ Y A M",
  },
  {
    "options": [
      "assets/images/nquestcard.png",
      "assets/images/yquestcard.png",
      "assets/images/tquestcard.png",
    ],
    "answerindex": 0,
    "questImageQuestion": "assets/images/fillin-pensil.png",
    "questionText": "P E _ S I L",
  },
  {
    "options": [
      "assets/images/nquestcard.png",
      "assets/images/yquestcard.png",
      "assets/images/tquestcard.png",
    ],
    "answerindex": 2,
    "questImageQuestion": "assets/images/fillin-telur.png",
    "questionText": "_ E L U R",
  },
  {
    "options": [
      "assets/images/jquestcard.png",
      "assets/images/kquestcard.png",
      "assets/images/lquestcard.png",
    ],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fillin-kapal.png",
    "questionText": "_ A P A L",
  },
  {
    "options": [
      "assets/images/aquestcard.png",
      "assets/images/pquestcard.png",
      "assets/images/bquestcard.png",
    ],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fillin-apel.png",
    "questionText": "A _ E L",
  },
  {
    "options": [
      "assets/images/uquestcard.png",
      "assets/images/wquestcard.png",
      "assets/images/rquestcard.png",
    ],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fillin-wortel.png",
    "questionText": "_ O R T E L",
  },
  {
    "options": [
      "assets/images/squestcard.png",
      "assets/images/oquestcard.png",
      "assets/images/dquestcard.png",
    ],
    "answerindex": 2,
    "questImageQuestion": "assets/images/fillin-kuda.png",
    "questionText": "K U _ A",
  },
  {
    "options": [
      "assets/images/hquestcard.png",
      "assets/images/iquestcard.png",
      "assets/images/mquestcard.png",
    ],
    "answerindex": 2,
    "questImageQuestion": "assets/images/fillin-motor.png",
    "questionText": "_ O T O R",
  },
  {
    "options": [
      "assets/images/uquestcard.png",
      "assets/images/wquestcard.png",
      "assets/images/rquestcard.png",
    ],
    "answerindex": 2,
    "questImageQuestion": "assets/images/fillin-kereta.png",
    "questionText": "K E _ E T A",
  },
  {
    "options": [
      "assets/images/zquestcard.png",
      "assets/images/wquestcard.png",
      "assets/images/nquestcard.png",
    ],
    "answerindex": 0,
    "questImageQuestion": "assets/images/fillin-zebra.png",
    "questionText": "_ E B R A",
  },
  {
    "options": [
      "assets/images/jquestcard.png",
      "assets/images/kquestcard.png",
      "assets/images/lquestcard.png",
    ],
    "answerindex": 2,
    "questImageQuestion": "assets/images/fillin-mobil.png",
    "questionText": "M O B I _",
  },
  {
    "options": [
      "assets/images/hquestcard.png",
      "assets/images/iquestcard.png",
      "assets/images/mquestcard.png",
    ],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fillin-sapi.png",
    "questionText": "S A P _",
  },
  {
    "options": [
      "assets/images/zquestcard.png",
      "assets/images/wquestcard.png",
      "assets/images/nquestcard.png",
    ],
    "answerindex": 2,
    "questImageQuestion": "assets/images/fillin-lilin.png",
    "questionText": "L I L I _",
  },
  {
    "options": [
      "assets/images/nquestcard.png",
      "assets/images/yquestcard.png",
      "assets/images/tquestcard.png",
    ],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fillin-payung.png",
    "questionText": "P A _ U N G",
  },
  {
    "options": [
      "assets/images/squestcard.png",
      "assets/images/oquestcard.png",
      "assets/images/dquestcard.png",
    ],
    "answerindex": 0,
    "questImageQuestion": "assets/images/fillin-pisang.png",
    "questionText": "P I _ A N G",
  },
];

final List<Map<String, dynamic>> questionFillinWordData = [
  {
    "options": [
      "assets/images/mau.png",
      "assets/images/perkenalkan.png",
      "assets/images/terimakasih.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "NAMAKU", "isanswer": false},
      {"content": "GIEL", "isanswer": false},
    ],
    "questionText": "assets/images/akucard.png",
  },
  {
    "options": [
      "assets/images/aku.png",
      "assets/images/becak.png",
      "assets/images/nama.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "KAMU", "isanswer": false},
      {"content": "SIAPA", "isanswer": false},
    ],
    "questionText": "assets/images/terimakasihcard.png",
  },
  {
    "options": [
      "assets/images/mobil.png",
      "assets/images/tidakmau.png",
      "assets/images/senang.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "AKU", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "MELAKUKAN HAL BURUK", "isanswer": false},
    ],
    "questionText": "assets/images/hallocard.png",
  },
  {
    "options": [
      "assets/images/hallo.png",
      "assets/images/bus-fillin.png",
      "assets/images/tolong.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "KITA MENGUCAPKAN", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "SAAT BUTUH BANTUAN", "isanswer": false},
    ],
    "questionText": "assets/images/senangcard.png",
  },
  {
    "options": [
      "assets/images/aku.png",
      "assets/images/becak.png",
      "assets/images/nama.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "AYO BERKELILING", "isanswer": false},
      {"content": "YOGYAKARTA NAIK", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/biscard.png",
  },
  {
    "options": [
      "assets/images/senin.png",
      "assets/images/minggu.png",
      "assets/images/pagi.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "MERUPAKAN HARI", "isanswer": false},
      {"content": "SEBELUM HARI MINGGU", "isanswer": false},
    ],
    "questionText": "assets/images/tolongcard.png",
  },
  {
    "options": [
      "assets/images/jumat.png",
      "assets/images/samasama.png",
      "assets/images/sehat.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "BALASAN DARI KATA TERIMA", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "KASIH ADALAH", "isanswer": false},
    ],
    "questionText": "assets/images/senangcard.png",
  },
  {
    "options": [
      "assets/images/bertemu.png",
      "assets/images/selasa.png",
      "assets/images/rabu.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "HARI SETELAH HARI SENIN", "isanswer": false},
      {"content": "ADALAH HARI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/terimakasihcard.png",
  },
  {
    "options": [
      "assets/images/berteman.png",
      "assets/images/kamis.png",
      "assets/images/sampai.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "SEKOLAH LIBUR DARI HARI", "isanswer": false},
      {"content": "SABTU", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "HARI MINGGU", "isanswer": false},
    ],
    "questionText": "assets/images/namacard.png",
  },
  {
    "options": [
      "assets/images/senin.png",
      "assets/images/minggu.png",
      "assets/images/sabtu.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "LIBURAN KELUARGA", "isanswer": false},
      {"content": "BIASANYA PADA HARI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mobilcard.png",
  },
  {
    "options": [
      "assets/images/berteman.png",
      "assets/images/kamis.png",
      "assets/images/sampai.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "APAKAH KAMU MAU", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "DENGANKU?", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/bertemu.png",
      "assets/images/selasa.png",
      "assets/images/rabu.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "HARI SETELAH HARI SELASA", "isanswer": false},
      {"content": "ADALAH HARI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/jumat.png",
      "assets/images/samasama.png",
      "assets/images/sehat.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "HARI SETELAH HARI KAMIS", "isanswer": false},
      {"content": "ADALAH HARI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/senin.png",
      "assets/images/minggu.png",
      "assets/images/sabtu.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "HARI PERTAMA SEKOLAH", "isanswer": false},
      {"content": "DIMULAI PADA HARI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/berteman.png",
      "assets/images/kamis.png",
      "assets/images/sampai.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "AKU MEMILIKI JADWAL", "isanswer": false},
      {"content": "RENANG PADA HARI", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/bertemu.png",
      "assets/images/selasa.png",
      "assets/images/rabu.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "AKU", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "DENGANNYA", "isanswer": false},
      {"content": "TADI DI PERPUSATAKAAN", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/jumat.png",
      "assets/images/samasama.png",
      "assets/images/sehat.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "AKU BEROLAHRAGA SUPAYA", "isanswer": false},
      {"content": "TUBUH MENJADI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/dimana.png",
      "assets/images/kapan.png",
      "assets/images/belajar.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "KAMU", "isanswer": false},
      {"content": "ULANG TAHUN?", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/berapa.png",
      "assets/images/sore.png",
      "assets/images/siang.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "AKU MAKAN SIANG", "isanswer": false},
      {"content": "PADA WAKTU", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/siapa.png",
      "assets/images/malam.png",
      "assets/images/selamat.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "PAGI", "isanswer": false},
      {"content": "SEMUANYA", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/bermain.png",
      "assets/images/bagusbaik.png",
      "assets/images/pagi.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "HARI INI AKU", "isanswer": false},
      {"content": "MERASA", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/dimana.png",
      "assets/images/kapan.png",
      "assets/images/belajar.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "KAMU", "isanswer": false},
      {"content": "TINGGAL?", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/berapa.png",
      "assets/images/sore.png",
      "assets/images/siang.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "HARGA", "isanswer": false},
      {"content": "BUKU INI", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/siapa.png",
      "assets/images/malam.png",
      "assets/images/selamat.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "NAMA", "isanswer": false},
      {"content": "KAMU", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/bermain.png",
      "assets/images/bagusbaik.png",
      "assets/images/pagi.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "AKU SENANG", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "BERSAMA TEMAN", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/dimana.png",
      "assets/images/kapan.png",
      "assets/images/belajar.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "AKU SUKA", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "SETIAP HARI", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/berapa.png",
      "assets/images/sore.png",
      "assets/images/siang.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "MATAHARI TERBENAM DI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "HARI", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/siapa.png",
      "assets/images/malam.png",
      "assets/images/selamat.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "AKU TIDUR SAAT", "isanswer": false},
      {"content": "HARI SUDAH", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/bermain.png",
      "assets/images/bagusbaik.png",
      "assets/images/pagi.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "AKU BANGN SAAT", "isanswer": false},
      {"content": "HARI MASIH", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/perkenalkan.png",
      "assets/images/sehat.png",
      "assets/images/belajar.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "HALLO!", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "NAMAKU GIEL", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/malam.png",
      "assets/images/senang.png",
      "assets/images/minggu.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "DIA TERLIHAT SANGAT", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "HARI INI", "isanswer": false},
    ],
    "questionText": "assets/images/maucard.png",
  },
  {
    "options": [
      "assets/images/nama.png",
      "assets/images/samasama.png",
      "assets/images/bagusbaik.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "JAWABAN KATA TERIMA", "isanswer": false},
      {"content": "KASIH ADALAH KATA", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/berteman.png",
      "assets/images/dimana.png",
      "assets/images/mobil.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "AKU MELIHAT SEBUAH", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "MERAH DI JALAN", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/perkenalkan.png",
      "assets/images/sehat.png",
      "assets/images/belajar.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "AKU HARUS MAKAN SAYUR", "isanswer": false},
      {"content": "AGAR TETAP", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/malam.png",
      "assets/images/senang.png",
      "assets/images/minggu.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "BULAN TERLIHAT INDAH DI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "HARI", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/nama.png",
      "assets/images/samasama.png",
      "assets/images/bagusbaik.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "AKU", "isanswer": false},
      {"content": "ADALAH ARIN", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/berteman.png",
      "assets/images/dimana.png",
      "assets/images/mobil.png",
    ],
    "answerindex": 0,
    "questions": [
      {"content": "AKU INGIN", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "DENGAN SEMUA ORANG", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/perkenalkan.png",
      "assets/images/sehat.png",
      "assets/images/belajar.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "KITA HARUS RAJIN", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "SUPAYA MENJADI PINTAR", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/malam.png",
      "assets/images/senang.png",
      "assets/images/minggu.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "HARI", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
      {"content": "AKU TIDAK KE SEKOLAH", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/nama.png",
      "assets/images/samasama.png",
      "assets/images/bagusbaik.png",
    ],
    "answerindex": 2,
    "questions": [
      {"content": "GAMBARMU TERLIHAT", "isanswer": false},
      {"content": "SANGAT", "isanswer": false},
      {"content": "_     ,", "isanswer": true},
    ],
    "questionText": "assets/images/mau.png",
  },
  {
    "options": [
      "assets/images/berteman.png",
      "assets/images/dimana.png",
      "assets/images/mobil.png",
    ],
    "answerindex": 1,
    "questions": [
      {"content": "_     ,", "isanswer": true},
      {"content": "RUMAHMU", "isanswer": false},
      {"content": "BERADA?", "isanswer": false},
    ],
    "questionText": "assets/images/mau.png",
  },
];
