final List<Map<String, dynamic>> questionData = [
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/aquestcard.png",
    "questImageAnswer": "assets/images/acard.png",
  },
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/bquestcard.png",
    "questImageAnswer": "assets/images/bcard.png",
  },
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 2,
    "questImageQuestion": "assets/images/cquestcard.png",
    "questImageAnswer": "assets/images/ccard.png",
  },
  {
    "options": ["A", "B", "C", "D"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/dquestcard.png",
    "questImageAnswer": "assets/images/dcard.png",
  },
  {
    "options": ["B", "C", "D", "E"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/equestcard.png",
    "questImageAnswer": "assets/images/ecard.png",
  },
  {
    "options": ["C", "F", "D", "E"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/fquestcard.png",
    "questImageAnswer": "assets/images/fcard.png",
  },
  {
    "options": ["D", "E", "G", "F"],
    "answerindex": 2,
    "questImageQuestion": "assets/images/gquestcard.png",
    "questImageAnswer": "assets/images/gcard.png",
  },
  {
    "options": ["H", "I", "J", "K"],
    "answerindex": 0,
    "questImageQuestion": "assets/images/hquestcard.png",
    "questImageAnswer": "assets/images/hcard.png",
  },
  {
    "options": ["H", "I", "J", "K"],
    "answerindex": 1,
    "questImageQuestion": "assets/images/iquestcard.png",
    "questImageAnswer": "assets/images/icard.png",
  },
  {
    "options": ["H", "I", "J", "L"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/jquestcard.png",
    "questImageAnswer": "assets/images/jcard.png",
  },
  {
    "options": ["H", "I", "J", "K"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/kquestcard.png",
    "questImageAnswer": "assets/images/kcard.png",
  },
  {
    "options": ["I", "J", "K", "L"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/lquestcard.png",
    "questImageAnswer": "assets/images/lcard.png",
  },
  {
    "options": ["J", "K", "L", "M"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/mquestcard.png",
    "questImageAnswer": "assets/images/mcard.png",
  },
  {
    "options": ["K", "L", "M", "N"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/nquestcard.png",
    "questImageAnswer": "assets/images/ncard.png",
  },
  {
    "options": ["L", "M", "N", "O"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/oquestcard.png",
    "questImageAnswer": "assets/images/ocard.png",
  },
  {
    "options": ["L", "M", "N", "P"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/pquestcard.png",
    "questImageAnswer": "assets/images/pcard.png",
  },
  {
    "options": ["M", "N", "P", "Q"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/qquestcard.png",
    "questImageAnswer": "assets/images/qcard.png",
  },
  {
    "options": ["N", "P", "Q", "R"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/rquestcard.png",
    "questImageAnswer": "assets/images/rcard.png",
  },
  {
    "options": ["P", "Q", "R", "S"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/squestcard.png",
    "questImageAnswer": "assets/images/scard.png",
  },
  {
    "options": ["Q", "R", "S", "T"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/tquestcard.png",
    "questImageAnswer": "assets/images/tcard.png",
  },
  {
    "options": ["R", "S", "T", "U"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/uquestcard.png",
    "questImageAnswer": "assets/images/ucard.png",
  },
  {
    "options": ["S", "T", "U", "V"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/vquestcard.png",
    "questImageAnswer": "assets/images/vcard.png",
  },
  {
    "options": ["T", "U", "V", "W"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/wquestcard.png",
    "questImageAnswer": "assets/images/wcard.png",
  },
  {
    "options": ["U", "V", "W", "X"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/xquestcard.png",
    "questImageAnswer": "assets/images/xcard.png",
  },
  {
    "options": ["V", "W", "X", "Y"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/yquestcard.png",
    "questImageAnswer": "assets/images/ycard.png",
  },
  {
    "options": ["W", "X", "Y", "Z"],
    "answerindex": 3,
    "questImageQuestion": "assets/images/zquestcard.png",
    "questImageAnswer": "assets/images/zcard.png",
  }
];
